included:
    - Examples
    - Sources
    - Tests

opt_in_rules:
    - anyobject_protocol
    - array_init
    - attributes
    - class_delegate_protocol
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - convenience_type
    - discouraged_assert
    - empty_collection_literal
    - empty_count
    - empty_string
    - empty_xctest_method
    - enum_case_associated_values_count
    - expiring_todo
    - explicit_enum_raw_value
    - explicit_top_level_acl
    - extension_access_modifier
    - fallthrough
    - fatal_error_message
    - file_header
    - file_name_no_space
    - file_types_order
    - first_where
    - force_unwrapping
    - identical_operands
    - inert_defer
    - is_disjoint
    - joined_default_parameter
    - last_where
    - legacy_multiple
    - legacy_random
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - missing_docs
    - modifier_order
    - multiline_arguments
    - multiline_function_chains
    - multiline_parameters
    - number_separator
    - operator_usage_whitespace
    - orphaned_doc_comment
    - pattern_matching_keywords
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - private_subject
    - private_unit_test
    - prohibited_interface_builder
    - reduce_into
    - redundant_nil_coalescing
    - single_test_class
    - sorted_first_last
    - sorted_imports
    - static_operator
    - switch_case_on_newline
    - test_case_accessibility
    - toggle_bool
    - trailing_closure
    - type_contents_order
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - untyped_error_in_catch
    - unused_import
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - yoda_condition

cyclomatic_complexity:
    ignores_case_statements: true

file_length:
    ignore_comment_only_lines: true

function_body_length:
    warning: 50

identifier_name:
    excluded:
      - x
      - y
      - id
      - iv
      - url

line_length:
    ignores_comments: true
    ignores_function_declarations: true
    ignores_interpolated_strings: true
    ignores_urls: true
