name:                                  checks

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  # pull request-sepcific steps.
  pull_request:
    name:                              Pull request
    runs-on:                           ubuntu-latest
    if:                                ${{ github.event.number }}

    steps:
      - name:                          Checkout
        uses:                          actions/checkout@v2
      # validate commits.
      - name:                          Validate commits
        uses:                          KevinDeJong-TomTom/commisery-action@master
        with:
          token:                       ${{ secrets.GITHUB_TOKEN }}
          pull_request:                ${{ github.event.number }}
      # create the changelog.
      - name:                          Changelog
        id:                            changelog
        uses:                          mrchief/universal-changelog-action@v1.3.0
        with:
          previousReleaseTagNameOrSha: ${{ github.event.pull_request.base.sha }}
          nextReleaseTagName:          ${{ github.event.number }}
          nextReleaseName:             ${{ github.event.number }}
      # update the pull request message body.
      - name:                          Update Pull Request Description
        if:                            ${{ steps.changelog.outputs.changelog }}
        uses:                          riskledger/update-pr-description@v2
        with:
          body:                        ${{ steps.changelog.outputs.changelog }}
          token:                       ${{ secrets.GITHUB_TOKEN }}

  # lint code.
  lint:
    name:                              Lint
    runs-on:                           ubuntu-latest

    steps:
      - name:                          Checkout
        uses:                          actions/checkout@v2
      # only lint on actual code changes.
      - uses:                          dorny/paths-filter@v2
        id:                            changes
        with:
          base:                        ${{ github.event.pull_request.base.sha || github.event.push.before }}
          ref:                         ${{ github.event.pull_request.head.sha || github.event.push.head }}
          filters:                     |
            src:
              - '**/*.swift'
      - name:                          Lint
        if:                            steps.changes.outputs.src == 'true'
        uses:                          norio-nomura/action-swiftlint@3.1.0
        with:
          args:                        --strict

  # build the library.
  build:
    name:                              Build
    needs:                             lint
    runs-on:                           macos-latest

    steps:
      - name:                          Checkout
        uses:                          actions/checkout@v2
      # only build on actual code changes.
      - uses:                          dorny/paths-filter@v2
        id:                            changes
        with:
          base:                        ${{ github.event.pull_request.base.sha || github.event.push.before }}
          ref:                         ${{ github.event.pull_request.head.sha || github.event.push.head }}
          filters:                     |
            src:
              - '**/*.swift'
      - name:                          Build
        if:                            steps.changes.outputs.src == 'true'
        run:                           swift build
