name:              push

on:
  push:
    branches:
      - main
      - bugfixes
      - development

jobs:
  # lint code.
  lint:
    name:          Lint
    runs-on:       ubuntu-latest

    steps:
      - name:      Checkout
        uses:      actions/checkout@v2
      - uses:      dorny/paths-filter@v2
        id:        changes
        with:
          filters: |
            src:
              - '**/*.swift'
      - name:      Lint
        if:        steps.changes.outputs.src == 'true'
        uses:      norio-nomura/action-swiftlint@3.1.0
        with:
          args:    --strict

  # build the library.
  build:
    name:          Build
    needs:         lint
    runs-on:       macos-latest

    steps:
      - name:      Checkout
        uses:      actions/checkout@v2
      - uses:      dorny/paths-filter@v2
        id:        changes
        with:
          filters: |
            src:
              - '**/*.swift'
      - name:      Build
        if:        steps.changes.outputs.src == 'true'
        run:       swift build
